import type { Metadata } from "next";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

import React from "react";
import MainRoot from "./main-root";
import ClientRoot from "./client-root";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <MainRoot>
          <ClientRoot>{children}</ClientRoot>
        </MainRoot>
      </body>
    </html>
  );
}
